# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-15 03:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.IntegerField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField(max_length=4)),
                ('image', models.BinaryField()),
                ('delivery_date', models.DateTimeField(default=datetime.datetime.now)),
                ('limit_date', models.DateField(default=datetime.date.today)),
                ('register_date', models.DateField(default=datetime.date.today)),
                ('id_seller', models.IntegerField(max_length=4)),
            ],
        ),
    ]
