# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_buyer', models.IntegerField()),
                ('direction', models.CharField(max_length=255, verbose_name=b'Direccion ')),
            ],
        ),
    ]
