# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-15 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='direction',
            field=models.TextField(max_length=255, verbose_name='Direccion '),
        ),
    ]
