# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name=b'Nombre ')),
                ('last_name', models.CharField(max_length=30, verbose_name=b'Apellido ')),
                ('email', models.CharField(max_length=50, verbose_name=b'Email ')),
                ('user_name', models.CharField(max_length=15, verbose_name=b'Nombre de Usuario ')),
                ('password', models.CharField(max_length=10)),
                ('cellphone', models.CharField(max_length=10, verbose_name=b'Celular ')),
                ('is_seller', models.BooleanField()),
                ('direction', models.CharField(max_length=255, verbose_name=b'Direccion ')),
            ],
        ),
    ]
