# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-15 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180406_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cellphone',
            field=models.CharField(max_length=10, verbose_name='Celular '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direction',
            field=models.TextField(max_length=255, verbose_name='Direccion '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_seller',
            field=models.BooleanField(verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Apellido '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_name',
            field=models.CharField(max_length=15, verbose_name='Nombre de Usuario '),
        ),
    ]
